name: Render Pinger_1

on:
  schedule:
    - cron: '*/8 * * * *'   # Every 8 minutes
  workflow_dispatch:        # Optional: Manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:

      - name: Test Ping
        run: echo "This is a test ping at $(date)"

      - name: Ping App 1
        run: |
          echo "Pinging Xorynx User..."
          curl -v https://connectsphere-ud6f.onrender.com/

      - name: Ping App 2
        run: |
          echo "Pinging Xorynx Official Work..."
          curl -v https://connectsphere-official.onrender.com/

      - name: Ping App 3
        run: |
          echo "Pinging Xorynx Official..."
          curl -v https://xorynx-official.onrender.com/

      - name: Ping App 4
        run: |
          echo "Pinging Xorynx Internship..."
          curl -v https://xorynx-internship.onrender.com/

      - name: Ping App 5
        run: |
          echo "Pinging Xorynx Silta..."
          curl -v https://xorynx-silta.onrender.com/
          